apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-service-monitor
  labels:
    Release: monitoring
    type: servicemonitor
spec:
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-frontendproxy
  endpoints:
    - port: tcp-service
      interval: 30s